In [15]:
import ollama
import pandas as pd
from yahoo_finance import MarketData
from news_embedder import NewsEmbedder

OLLAMA_HOST = "http://100.68.136.71:11434"

# Verifica se o modelo já está disponível antes de puxar
client = ollama.Client(host=OLLAMA_HOST)

# Etapa 2 — Engenharia de Features

Este notebook combina dados de mercado (Yahoo Finance) com embeddings de notícias (Ollama) em um dataset unificado para treinamento.

**Fontes de dados:**
- `yahoo_finance.py` → `MarketData.features()`: Close, Volume, retorno diário, médias móveis 7/21 dias, volatilidade 21 dias, lags 1-5
- `news_embedder.py` → `NewsEmbedder`: embeddings de 1024 dimensões via modelo `qwen3-embedding:4b`

**Agregação e alinhamento:**
- Notícias do mesmo dia são agregadas via média ponderada por recência (`_weighted_mean`)
- Embeddings são alinhados com preços via `merge_with_prices()` (left join + forward-fill para dias sem notícias)

**Dimensões finais do dataset:** 230 dias × 1.035 features (8 price + 1.024 embeddings + 3 PCA auxiliares)

**Saída:** `dataset_full.csv` — dataset completo pronto para treinamento

In [16]:
client.list().models

13:29:27 [INFO] HTTP Request: GET http://100.68.136.71:11434/api/tags "HTTP/1.1 200 OK"

[Model(model='qwen3-embedding:4b', modified_at=datetime.datetime(2026, 3, 16, 11, 3, 45, 563525, tzinfo=TzInfo(-10800)), digest='df5bd2e3c74cd8d069d21dc038f1b359fcdc9458fce1c99bd43c9eb1518ff907', size=2496704041, details=ModelDetails(parent_model='', format='gguf', family='qwen3', families=['qwen3'], parameter_size='4.0B', quantization_level='Q4_K_M')),
 Model(model='llama3.2:latest', modified_at=datetime.datetime(2026, 3, 2, 20, 16, 31, 728797, tzinfo=TzInfo(-10800)), digest='a80c4f17acd55265feec403c7aef86be0c25983ab279d83f3bcd3abbcb5b8b72', size=2019393189, details=ModelDetails(parent_model='', format='gguf', family='llama', families=['llama'], parameter_size='3.2B', quantization_level='Q4_K_M')),
 Model(model='lfm2.5-thinking:latest', modified_at=datetime.datetime(2026, 3, 2, 20, 12, 22, 506453, tzinfo=TzInfo(-10800)), digest='95bd9d45385f33bfe96d8b3651c8569e152f21f5bdb7c19894ffde650e9cf140', size=731163903, details=ModelDetails(parent_model='', format='gguf', family='lfm2', families=['lfm2'], parameter_size='1.2B', quantization_level='Q4_K_M')),
 Model(model='qwen3.5:4b', modified_at=datetime.datetime(2026, 3, 2, 17, 58, 54, 729827, tzinfo=TzInfo(-10800)), digest='2a654d98e6fba55d452b7043684e9b57a947e393bbffa62485a7aac05ee4eefd', size=3389983735, details=ModelDetails(parent_model='', format='gguf', family='qwen35', families=['qwen35'], parameter_size='4.7B', quantization_level='Q4_K_M')),
 Model(model='qwen3.5:0.8b', modified_at=datetime.datetime(2026, 3, 2, 17, 54, 4, 107946, tzinfo=TzInfo(-10800)), digest='f3817196d142eaf72ce79dfebe53dcb20bd21da87ce13e138a8f8e10a866b3a4', size=1036046583, details=ModelDetails(parent_model='', format='gguf', family='qwen35', families=['qwen35'], parameter_size='873.44M', quantization_level='Q8_0')),
 Model(model='kimi-k2.5:cloud', modified_at=datetime.datetime(2026, 3, 2, 14, 52, 46, 661198, tzinfo=TzInfo(-10800)), digest='6d1c3246c6080b61c87b543323760b8f36cb68cf4473080b9429d09e2a73ddb7', size=340, details=ModelDetails(parent_model='', format='', family='', families=None, parameter_size='', quantization_level='')),
 Model(model='qwen3-embedding:0.6b', modified_at=datetime.datetime(2026, 2, 3, 14, 4, 34, 109201, tzinfo=TzInfo(-10800)), digest='ac6da0dfba84a81fdbfbaf330198c33cd77c4cdfc53e8bc50eb581914a15621d', size=639150858, details=ModelDetails(parent_model='', format='gguf', family='qwen3', families=['qwen3'], parameter_size='595.78M', quantization_level='Q8_0')),
 Model(model='gpt-oss:20b-cloud', modified_at=datetime.datetime(2026, 2, 3, 12, 25, 25, 707291, tzinfo=TzInfo(-10800)), digest='875e8e3a629ad3c2e66f1f1c461e3d140474212f44a34f4687ae1d927db41690', size=381, details=ModelDetails(parent_model='', format='', family='gptoss', families=['gptoss'], parameter_size='20.9B', quantization_level='MXFP4'))]

In [23]:
embedding_model = "qwen3-embedding:0.6b"

In [24]:
modelos = [m.model for m in client.list().models]
if embedding_model not in modelos:
    print(f"Baixando {embedding_model}...")
    client.pull(embedding_model)

13:30:28 [INFO] HTTP Request: GET http://100.68.136.71:11434/api/tags "HTTP/1.1 200 OK"

In [ ]:

# Notícias
df_news = pd.read_json("../1.news/itub4_noticias.json", convert_dates=False)
articles  = df_news.to_dict(orient="records")

# Preços — período estendido para 5 anos (alinhado com dados de notícias desde 2021)
md      = MarketData("ITUB4.SA")
X_price = md.features(period="5y", lags=5)
y       = md.target(period="5y", horizon=5)

# Embedder
ne = NewsEmbedder(
    model=embedding_model,
    fields=["title", "excerpt", "content"],
    ollama_host=OLLAMA_HOST,
    cache_path="embeddings_cache.npz",
    summarizer_model='lfm2.5-thinking'
)

In [29]:
df_news

,id,date,modified,title,link,excerpt,content,author_id,author_name,hat,categories,tags,keywords
0,3252277,2026-03-16T13:08:54,2026-03-16T13:09:01,Cosan (CSAN3): o que esperar da holding após r...,https://www.infomoney.com.br/mercados/cosan-cs...,Cosan vem passando por um processo de reestrut...,Após a Cosan (CSAN3) divulgar seus resultados ...,54205,Felipe Moreira,De olho em CSAN3,[1],"[332, 2691, 629, 210752, 381]","[Ações, Cosan, Goldman Sachs, Recomendação neu..."
1,3251628,2026-03-16T10:56:56,2026-03-16T10:57:01,"Com maior peso de estatais na AL, Brasil abre ...",https://www.infomoney.com.br/mercados/com-maio...,Banco atualizou sua cesta de ações de estatais...,"De olho na proximidade do pleito de outubro, o...",25,Lara Rizério,Cenário para eleições,[1],"[288694, 1172, 1414, 1440, 1880, 12, 2517]","[Axia, Bradesco BBI, Embraer, Estatais, MSCI, ..."
2,3250267,2026-03-16T06:04:39,2026-03-16T06:06:01,"Prévia do PIB, indústria nos EUA, conflito no ...",https://www.infomoney.com.br/mercados/previa-p...,InfoMoney reúne as principais informações que ...,A sessão desta segunda-feira (16) atualiza mai...,620517,"Erick Souza, Felipe Moreira",O que vai mexer com a Bolsa,[1],"[986, 382, 1383, 283800, 539, 192609, 194340, ...","[5 Assuntos, Banco Central, Donald Trump, Elei..."
3,3250055,2026-03-13T17:51:27,2026-03-13T18:19:20,Ibovespa fecha abaixo de 178 mil pontos sem al...,https://www.infomoney.com.br/mercados/ibovespa...,O volume financeiro nesta sexta-feira somou R$...,"SÃO PAULO, 13 Mar (Reuters) – O Ibovespa fecho...",43,Reuters,Mercado doméstico,[1],"[653, 1649, 2314]","[Ibovespa, Irã, Trader]"
4,3250081,2026-03-13T18:13:47,2026-03-13T18:13:49,"Previ recebeu R$ 4,4 bi em dividendos e JCP e ...",https://www.infomoney.com.br/onde-investir/pre...,Dividendos e juros sobre capital próprio ajuda...,"A Previ recebeu R$ 4,4 bilhões em dividendos e...",44,Estadão Conteúdo,Dividendos e JCP,[2476],"[527, 1695, 814]","[Dividendos, JCP, Previ]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2567,1626362,2021-04-20T08:20:50,2021-04-20T09:19:21,Dados de produção da Vale e de vendas do Carre...,https://www.infomoney.com.br/mercados/dados-de...,Confira os destaques do noticiário corporativo...,SÃO PAULO – O noticiário corporativo desta ter...,293,Equipe InfoMoney,Radar InfoMoney,[1],"[332, 1227, 2803, 2068, 2517]","[Ações, Carrefour, Linx, Radar InfoMoney, Vale]"
2568,1625265,2021-04-16T12:23:51,2021-04-16T12:25:03,B3 mantém Locaweb (LWSA3) e inclui units do Ba...,https://www.infomoney.com.br/mercados/b3-mante...,"Com isso, caso confirmada na próxima prévia, a...",A B3 divulgou nesta sexta-feira (16) a segunda...,293,Equipe InfoMoney,Nova carteira,[1],"[332, 2840, 653, 1742]","[Ações, Banco Inter, Ibovespa, Locaweb]"
2569,1624516,2021-04-15T17:44:23,2021-04-15T17:45:41,"Ações de Vale e frigoríficos voltam a subir, P...",https://www.infomoney.com.br/mercados/acoes-de...,Confira os destaques da B3 na sessão desta qui...,SÃO PAULO – O grande destaque do mercado nesta...,25,Lara Rizério,Destaques da Bolsa,[1],"[332, 2782, 2445, 2614, 2495, 2712, 2490]","[Ações, Arezzo, Bradesco, Cia Hering, Itaú Uni..."
2570,1623847,2021-04-14T17:40:46,2021-04-14T18:01:26,"Ações de Vale, siderúrgicas, Petrobras e frigo...",https://www.infomoney.com.br/mercados/acoes-da...,Confira os destaques da B3 na sessão desta qua...,SÃO PAULO – O destaque do Ibovespa na sessão d...,25,Lara Rizério,Destaques da Bolsa,[1],"[332, 2550, 2687, 2827, 2713, 2517]","[Ações, Americanas, B2W Digital, CVC Brasil, J..."
2571,1622617,2021-04-12T17:41:05,2021-04-13T12:36:07,Ação do Pão de Açúcar salta quase 10%; Braskem...,https://www.infomoney.com.br/mercados/acoes-da...,Confira os destaques da B3 na sessão desta seg...,SÃO PAULO – O grande destaque de alta de ações...,25,Lara Rizério,Destaques da Bolsa,[1],"[332, 1179, 23598, 2770, 3433, 1972, 12, 163837]","[Ações, Braskem, Cessão Onerosa, Fleury, Hyper..."

In [30]:
# Dataset final
X_full = ne.merge_with_prices(X_price, articles)
df     = X_full.join(y).dropna()
X      = df.drop(columns=["target"])
y      = df["target"]

print(f"Shape final: {X.shape}")  # (dias, price_features + 768 emb dims)

13:33:24 [INFO] Iniciando embedding de 2572 artigos com 'qwen3-embedding:0.6b'
13:33:25 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:25 [INFO]   [   1/2572] 2026-03-16 | embed |   0.4s | ETA 17m36s | chars=6562
13:33:25 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:25 [INFO]   [   2/2572] 2026-03-16 | embed |   0.3s | ETA 14m46s | chars=5344
13:33:25 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:25 [INFO]   [   3/2572] 2026-03-16 | embed |   0.3s | ETA 14m27s | chars=5748
13:33:26 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:26 [INFO]   [   4/2572] 2026-03-13 | embed |   0.3s | ETA 14m18s | chars=5408
13:33:26 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:26 [INFO]   [   5/2572] 2026-03-13 | embed |   0.1s | ETA 12m36s | chars=1048
13:33:27 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:27 [INFO]   [   6/2572] 2026-03-13 | embed |   0.9s | ETA 16m42s | chars=50000
13:33:27 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:27 [INFO]   [   7/2572] 2026-03-13 | embed |   0.3s | ETA 15m55s | chars=3972
13:33:27 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:27 [INFO]   [   8/2572] 2026-03-13 | embed |   0.3s | ETA 15m44s | chars=4599
13:33:28 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:28 [INFO]   [   9/2572] 2026-03-11 | embed |   0.3s | ETA 15m29s | chars=4933
13:33:28 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:28 [INFO]   [  10/2572] 2026-03-11 | embed |   0.2s | ETA 14m48s | chars=3412
13:33:28 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:28 [INFO]   [  11/2572] 2026-03-10 | embed |   0.3s | ETA 14m43s | chars=5556
13:33:28 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:28 [INFO]   [  12/2572] 2026-03-10 | embed |   0.4s | ETA 14m54s | chars=7130
13:33:29 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:29 [INFO]   [  13/2572] 2026-03-09 | embed |   0.2s | ETA 14m32s | chars=3400
13:33:29 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:29 [INFO]   [  14/2572] 2026-03-09 | embed |   0.4s | ETA 14m34s | chars=6443
13:33:29 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:29 [INFO]   [  15/2572] 2026-03-09 | embed |   0.3s | ETA 14m29s | chars=5014
13:33:30 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:30 [INFO]   [  16/2572] 2026-03-06 | embed |   0.3s | ETA 14m27s | chars=5331
13:33:30 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:30 [INFO]   [  17/2572] 2026-03-06 | embed |   0.2s | ETA 14m06s | chars=3069
13:33:30 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:30 [INFO]   [  18/2572] 2026-03-05 | embed |   0.2s | ETA 13m53s | chars=3524
13:33:31 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:31 [INFO]   [  19/2572] 2026-03-05 | embed |   0.4s | ETA 13m56s | chars=6387
13:33:31 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:31 [INFO]   [  20/2572] 2026-03-04 | embed |   0.3s | ETA 13m47s | chars=4000
13:33:31 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:31 [INFO]   [  21/2572] 2026-03-04 | embed |   0.2s | ETA 13m28s | chars=2198
13:33:32 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:32 [INFO]   [  22/2572] 2026-01-26 | embed |   0.7s | ETA 14m13s | chars=5302
13:33:32 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:32 [INFO]   [  23/2572] 2026-03-04 | embed |   0.1s | ETA 13m50s | chars=826
13:33:32 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:32 [INFO]   [  24/2572] 2026-03-03 | embed |   0.5s | ETA 14m06s | chars=5568
13:33:32 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:32 [INFO]   [  25/2572] 2026-03-04 | embed |   0.2s | ETA 13m53s | chars=3342
13:33:33 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:33 [INFO]   [  26/2572] 2026-03-02 | embed |   0.4s | ETA 13m56s | chars=6727
13:33:33 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:33 [INFO]   [  27/2572] 2026-03-02 | embed |   0.3s | ETA 13m57s | chars=5684
13:33:34 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:34 [INFO]   [  28/2572] 2026-03-03 | embed |   0.4s | ETA 14m03s | chars=3761
13:33:34 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:34 [INFO]   [  29/2572] 2026-03-02 | embed |   0.3s | ETA 13m57s | chars=4398
13:33:35 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:35 [INFO]   [  30/2572] 2026-02-27 | embed |   0.8s | ETA 14m37s | chars=15669
13:33:35 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:35 [INFO]   [  31/2572] 2026-02-27 | embed |   0.3s | ETA 14m35s | chars=5230
13:33:35 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:35 [INFO]   [  32/2572] 2026-02-27 | embed |   0.1s | ETA 14m19s | chars=1296
13:33:35 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:35 [INFO]   [  33/2572] 2026-02-27 | embed |   0.2s | ETA 14m04s | chars=1704
13:33:36 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:36 [INFO]   [  34/2572] 2026-02-27 | embed |   0.4s | ETA 14m07s | chars=7128
13:33:36 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:36 [INFO]   [  35/2572] 2026-02-26 | embed |   0.1s | ETA 13m51s | chars=821
13:33:36 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:36 [INFO]   [  36/2572] 2026-02-26 | embed |   0.3s | ETA 13m48s | chars=4582
13:33:36 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:36 [INFO]   [  37/2572] 2026-02-26 | embed |   0.3s | ETA 13m44s | chars=4866
13:33:37 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:37 [INFO]   [  38/2572] 2026-02-25 | embed |   0.3s | ETA 13m40s | chars=4189
13:33:37 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:37 [INFO]   [  39/2572] 2026-02-25 | embed |   0.3s | ETA 13m35s | chars=4338
13:33:37 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:37 [INFO]   [  40/2572] 2026-02-25 | embed |   0.3s | ETA 13m31s | chars=4113
13:33:38 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:38 [INFO]   [  41/2572] 2026-02-24 | embed |   0.4s | ETA 13m34s | chars=7012
13:33:38 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:38 [INFO]   [  42/2572] 2026-02-24 | embed |   0.3s | ETA 13m31s | chars=4271
13:33:38 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:38 [INFO]   [  43/2572] 2026-02-24 | embed |   0.1s | ETA 13m20s | chars=1435
13:33:38 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:38 [INFO]   [  44/2572] 2026-02-24 | embed |   0.3s | ETA 13m17s | chars=5097
13:33:39 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:39 [INFO]   [  45/2572] 2026-02-23 | embed |   0.3s | ETA 13m19s | chars=6080
13:33:39 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:39 [INFO]   [  46/2572] 2026-02-23 | embed |   0.3s | ETA 13m18s | chars=5452
13:33:39 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:39 [INFO]   [  47/2572] 2026-02-23 | embed |   0.3s | ETA 13m16s | chars=4943
13:33:39 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:39 [INFO]   [  48/2572] 2026-02-20 | embed |   0.3s | ETA 13m17s | chars=6221
13:33:40 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:40 [INFO]   [  49/2572] 2026-02-20 | embed |   0.2s | ETA 13m11s | chars=2945
13:33:40 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:40 [INFO]   [  50/2572] 2026-02-20 | embed |   0.3s | ETA 13m09s | chars=5109
13:33:40 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:40 [INFO]   [  51/2572] 2026-02-19 | embed |   0.3s | ETA 13m05s | chars=4152
13:33:41 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:41 [INFO]   [  52/2572] 2026-02-19 | embed |   0.3s | ETA 13m04s | chars=5040
13:33:41 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:41 [INFO]   [  53/2572] 2026-02-18 | embed |   0.3s | ETA 13m02s | chars=4373
13:33:41 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:41 [INFO]   [  54/2572] 2026-02-18 | embed |   0.3s | ETA 13m01s | chars=5020
13:33:42 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:42 [INFO]   [  55/2572] 2026-02-18 | embed |   0.8s | ETA 13m23s | chars=16472
13:33:42 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:42 [INFO]   [  56/2572] 2026-02-13 | embed |   0.4s | ETA 13m25s | chars=6206
13:33:43 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:43 [INFO]   [  57/2572] 2026-02-13 | embed |   0.3s | ETA 13m24s | chars=4832
13:33:43 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:43 [INFO]   [  58/2572] 2026-02-12 | embed |   0.3s | ETA 13m23s | chars=5154
13:33:43 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:43 [INFO]   [  59/2572] 2026-02-12 | embed |   0.3s | ETA 13m22s | chars=5520
13:33:44 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:44 [INFO]   [  60/2572] 2026-02-11 | embed |   0.4s | ETA 13m24s | chars=6576
13:33:44 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:44 [INFO]   [  61/2572] 2026-02-11 | embed |   0.3s | ETA 13m24s | chars=5558
13:33:44 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:44 [INFO]   [  62/2572] 2026-02-11 | embed |   0.2s | ETA 13m17s | chars=1744
13:33:44 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:44 [INFO]   [  63/2572] 2026-02-11 | embed |   0.4s | ETA 13m19s | chars=7335
13:33:45 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:45 [INFO]   [  64/2572] 2026-02-10 | embed |   0.3s | ETA 13m19s | chars=5302
13:33:45 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:45 [INFO]   [  65/2572] 2026-02-10 | embed |   0.3s | ETA 13m20s | chars=6170
13:33:45 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:45 [INFO]   [  66/2572] 2026-02-06 | embed |   0.2s | ETA 13m14s | chars=2501
13:33:46 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:46 [INFO]   [  67/2572] 2026-02-09 | embed |   0.3s | ETA 13m12s | chars=4310
13:33:46 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:46 [INFO]   [  68/2572] 2026-02-09 | embed |   0.3s | ETA 13m11s | chars=5882
13:33:46 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:46 [INFO]   [  69/2572] 2026-02-10 | embed |   0.2s | ETA 13m06s | chars=2322
13:33:46 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:46 [INFO]   [  70/2572] 2026-02-09 | embed |   0.2s | ETA 13m01s | chars=2447
13:33:46 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:46 [INFO]   [  71/2572] 2026-02-09 | embed |   0.1s | ETA 12m55s | chars=1768
13:33:47 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:47 [INFO]   [  72/2572] 2026-02-09 | embed |   0.3s | ETA 12m54s | chars=5024
13:33:47 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:47 [INFO]   [  73/2572] 2026-02-09 | embed |   0.5s | ETA 13m00s | chars=8349
13:33:47 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:47 [INFO]   [  74/2572] 2026-02-09 | embed |   0.3s | ETA 13m00s | chars=5638
13:33:48 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:48 [INFO]   [  75/2572] 2026-02-09 | embed |   0.1s | ETA 12m54s | chars=1040
13:33:48 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:48 [INFO]   [  76/2572] 2026-02-06 | embed |   0.4s | ETA 12m58s | chars=7930
13:33:48 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:48 [INFO]   [  77/2572] 2026-02-06 | embed |   0.3s | ETA 12m57s | chars=4798
13:33:49 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:49 [INFO]   [  78/2572] 2026-02-06 | embed |   0.3s | ETA 12m57s | chars=5444
13:33:49 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:49 [INFO]   [  79/2572] 2026-02-06 | embed |   0.3s | ETA 12m55s | chars=5064
13:33:49 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:49 [INFO]   [  80/2572] 2026-02-06 | embed |   0.2s | ETA 12m50s | chars=1683
13:33:49 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:49 [INFO]   [  81/2572] 2026-02-06 | embed |   0.3s | ETA 12m49s | chars=4704
13:33:50 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:50 [INFO]   [  82/2572] 2026-02-05 | embed |   0.4s | ETA 12m52s | chars=7000
13:33:50 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:50 [INFO]   [  83/2572] 2026-02-05 | embed |   0.3s | ETA 12m49s | chars=4234
13:33:50 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:50 [INFO]   [  84/2572] 2026-02-05 | embed |   0.4s | ETA 12m51s | chars=7051
13:33:51 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:51 [INFO]   [  85/2572] 2026-02-05 | embed |   0.3s | ETA 12m51s | chars=5087
13:33:51 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:51 [INFO]   [  86/2572] 2026-02-05 | embed |   0.2s | ETA 12m47s | chars=2509
13:33:51 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:51 [INFO]   [  87/2572] 2026-02-05 | embed |   0.2s | ETA 12m44s | chars=4068
13:33:51 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:51 [INFO]   [  88/2572] 2026-02-05 | embed |   0.2s | ETA 12m41s | chars=3026
13:33:52 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:52 [INFO]   [  89/2572] 2026-02-05 | embed |   0.2s | ETA 12m39s | chars=3835
13:33:52 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:52 [INFO]   [  90/2572] 2026-02-05 | embed |   0.1s | ETA 12m34s | chars=1237
13:33:52 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:52 [INFO]   [  91/2572] 2026-02-05 | embed |   0.3s | ETA 12m32s | chars=4054
13:33:52 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:52 [INFO]   [  92/2572] 2026-02-05 | embed |   0.3s | ETA 12m32s | chars=5141
13:33:53 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:53 [INFO]   [  93/2572] 2026-02-05 | embed |   0.3s | ETA 12m33s | chars=6350
13:33:53 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:53 [INFO]   [  94/2572] 2026-02-04 | embed |   0.2s | ETA 12m31s | chars=3354
13:33:53 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:53 [INFO]   [  95/2572] 2026-02-04 | embed |   0.3s | ETA 12m31s | chars=5865
13:33:53 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:53 [INFO]   [  96/2572] 2026-02-04 | embed |   0.3s | ETA 12m31s | chars=5960
13:33:54 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:54 [INFO]   [  97/2572] 2026-02-04 | embed |   0.2s | ETA 12m29s | chars=3456
13:33:54 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:54 [INFO]   [  98/2572] 2026-02-04 | embed |   0.2s | ETA 12m26s | chars=3272
13:33:54 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:54 [INFO]   [  99/2572] 2026-02-04 | embed |   0.2s | ETA 12m22s | chars=2554
13:33:54 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:54 [INFO]   [ 100/2572] 2026-02-04 | embed |   0.2s | ETA 12m19s | chars=2607
13:33:55 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:55 [INFO]   [ 101/2572] 2026-02-04 | embed |   0.3s | ETA 12m19s | chars=4992
13:33:55 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:55 [INFO]   [ 102/2572] 2026-02-04 | embed |   0.3s | ETA 12m18s | chars=4311
13:33:55 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:55 [INFO]   [ 103/2572] 2026-02-04 | embed |   0.3s | ETA 12m18s | chars=5539
13:33:55 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:55 [INFO]   [ 104/2572] 2026-02-03 | embed |   0.2s | ETA 12m17s | chars=3906
13:33:56 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:56 [INFO]   [ 105/2572] 2026-02-03 | embed |   0.8s | ETA 12m28s | chars=19512
13:33:57 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:57 [INFO]   [ 106/2572] 2026-02-03 | embed |   0.9s | ETA 12m41s | chars=50000
13:33:58 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:58 [INFO]   [ 107/2572] 2026-02-04 | embed |   0.6s | ETA 12m47s | chars=5012
13:33:58 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:58 [INFO]   [ 108/2572] 2026-02-02 | embed |   0.3s | ETA 12m47s | chars=5859
13:33:58 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:58 [INFO]   [ 109/2572] 2026-02-02 | embed |   0.2s | ETA 12m45s | chars=3575
13:33:59 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:59 [INFO]   [ 110/2572] 2026-02-02 | embed |   0.3s | ETA 12m44s | chars=5255
13:33:59 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:59 [INFO]   [ 111/2572] 2026-02-03 | embed |   0.2s | ETA 12m42s | chars=3467
13:33:59 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:59 [INFO]   [ 112/2572] 2026-02-03 | embed |   0.2s | ETA 12m38s | chars=1662
13:33:59 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:33:59 [INFO]   [ 113/2572] 2026-02-02 | embed |   0.1s | ETA 12m34s | chars=1336
13:34:00 [INFO] HTTP Request: POST http://100.68.136.71:11434/api/embed "HTTP/1.1 200 OK"
13:34:00 [INFO]   [ 114/2572] 2026-01-30 | embed |   0.8s | ETA 12m44s | chars=14524

Shape final: (225, 1035)

In [31]:
X_full

,Close,Volume,return,ma7,ma21,std21,lag_1,lag_2,lag_3,lag_4,...,emb_1014,emb_1015,emb_1016,emb_1017,emb_1018,emb_1019,emb_1020,emb_1021,emb_1022,emb_1023
Date,,,,,,,,,,,,,,,,,,,,,
2025-04-14,28.989862,27027200,0.016347,28.325033,28.552147,0.372174,28.523584,28.380116,28.496687,27.985571,...,0.031040,-0.002682,-0.000366,-0.041628,-0.027340,0.006508,0.001079,0.026077,0.000236,-0.036171
2025-04-15,29.357506,25716216,0.012682,28.529990,28.579081,0.409033,28.989862,28.523584,28.380116,28.496687,...,0.031142,0.001516,-0.003609,-0.030854,-0.026495,0.009638,-0.025911,-0.011695,0.016893,-0.050896
2025-04-16,29.312668,32431301,-0.001527,28.720856,28.596509,0.432597,29.357506,28.989862,28.523584,28.380116,...,0.040072,-0.000547,0.011218,-0.001519,-0.012881,-0.009819,0.004554,0.018012,0.017389,-0.034635
2025-04-17,29.366468,20502356,0.001835,28.918127,28.613084,0.455626,29.312668,29.357506,28.989862,28.523584,...,0.018080,-0.003437,-0.018135,-0.022424,-0.018967,-0.006076,0.014465,-0.001867,0.029521,-0.065849
2025-04-22,29.940351,21624747,0.019542,29.124365,28.669790,0.539787,29.366468,29.312668,29.357506,28.989862,...,0.007268,-0.018829,-0.015511,-0.005094,-0.007859,0.000201,-0.007234,-0.005571,-0.010946,-0.023275
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-10,43.799999,50383100,0.014829,44.101428,46.711363,2.073892,43.160000,42.930000,43.509998,45.009998,...,0.016510,0.004368,-0.024688,-0.041406,0.005131,0.007449,-0.005965,-0.003189,0.005549,-0.068453
2026-03-11,43.889999,18482600,0.002055,43.811428,46.576037,2.163281,43.799999,43.160000,42.930000,43.509998,...,0.031070,0.018682,0.002019,-0.039785,-0.017665,0.000604,0.010232,-0.033142,0.020925,-0.046223
2026-03-12,42.689999,27095200,-0.027341,43.569999,46.309312,2.283212,43.889999,43.799999,43.160000,42.930000,...,0.031070,0.018682,0.002019,-0.039785,-0.017665,0.000604,0.010232,-0.033142,0.020925,-0.046223
2026-03-13,42.400002,24896600,-0.006793,43.197142,46.023542,2.381732,42.689999,43.889999,43.799999,43.160000,...,0.029562,0.016438,-0.019549,-0.017164,-0.008670,-0.002628,-0.004972,-0.007481,0.010742,-0.027454
2026-03-16,43.000000,7846000,0.014151,43.124286,45.721122,2.340977,42.400002,42.689999,43.889999,43.799999,...,0.012914,0.040775,0.002258,-0.018842,-0.031168,0.001763,-0.006106,0.002091,0.009380,0.001340

In [32]:
X_full.to_csv("dataset_full.csv", index=True)